export {IngresarDatosP,  IngresarDatosTP, IngresarDatosR} from "./Funciones/Crear"
export {initializeDatabase} from "./initializeDatabase"
// export { BuscarPaciente, BuscarTipoExamen, BuscarResultado } from "./Funciones/Buscar"
// export{ModificarPaciente, ModificarResultado, ModificarTipoExamen} from "./Funciones/Modificar"
// export { EliminarPaciente, EliminarResultado, EliminarTipoExamen } from "./Funciones/Eliminar"
